// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	googlesheetsv1 "github.com/grafana/google-sheets-datasource/pkg/apis/googlesheets/v1"
	clientset "github.com/grafana/google-sheets-datasource/pkg/client/clientset/clientset"
	internalinterfaces "github.com/grafana/google-sheets-datasource/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/grafana/google-sheets-datasource/pkg/client/listers/googlesheets/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DatasourceInformer provides access to a shared informer and lister for
// Datasources.
type DatasourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DatasourceLister
}

type datasourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDatasourceInformer constructs a new informer for Datasource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDatasourceInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDatasourceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDatasourceInformer constructs a new informer for Datasource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDatasourceInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GooglesheetsV1().Datasources(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GooglesheetsV1().Datasources(namespace).Watch(context.TODO(), options)
			},
		},
		&googlesheetsv1.Datasource{},
		resyncPeriod,
		indexers,
	)
}

func (f *datasourceInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDatasourceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *datasourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&googlesheetsv1.Datasource{}, f.defaultInformer)
}

func (f *datasourceInformer) Lister() v1.DatasourceLister {
	return v1.NewDatasourceLister(f.Informer().GetIndexer())
}
