apiVersion: v1
kind: Service
metadata:
  name: ext-api
  namespace: google-sheets
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - port: 6443 # seems to not matter. The port in APIService is what is used.
      name: https
