// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1 "github.com/grafana/google-sheets-datasource/pkg/apis/googlesheets/v1"
	googlesheetsv1 "github.com/grafana/google-sheets-datasource/pkg/client/applyconfiguration/googlesheets/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=googlesheets.ext.grafana.com, Version=v1
	case v1.SchemeGroupVersion.WithKind("Datasource"):
		return &googlesheetsv1.DatasourceApplyConfiguration{}

	}
	return nil
}
