// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by lister-gen. DO NOT EDIT.

package v1

// DatasourceListerExpansion allows custom methods to be added to
// DatasourceLister.
type DatasourceListerExpansion interface{}

// DatasourceNamespaceListerExpansion allows custom methods to be added to
// DatasourceNamespaceLister.
type DatasourceNamespaceListerExpansion interface{}
