name: "Publish artifact to GCS"
description: "Publish an artifact to GCS"

inputs:
  directory:
    required: true
    description: "The directory to publish"
  # module:
  #   required: true
  #   description: "Path to your plugin module.ts file. Usually ./src/module.ts"
  # comment-pr:
  #   description: "If running the action inside a pull_request write a comment with the check output. yes or no"
  #   default: "yes"
  #   required: false
  # skip-comment-if-compatible:
  #   description: "If comment-pr is enabled, skip the message if the result is favorable. yes or no"
  #   default: "no"
  #   required: false
  # fail-if-incompatible:
  #   description: "Fail the job if levitate finds incompatibilities. yes or no"
  #   default: "no"
  #   required: false
  # targets:
  #   description: "List of packages to test compatibility against"
  #   default: "@grafana/data,@grafana/ui,@grafana/runtime,@grafana/schema,@grafana/e2e-selectors,@grafana/experimental"
  #   required: false

runs:
  if: ${{ github.event.organization.login == 'grafana' }}
  runs-on: ubuntu-latest
  steps:
    - id: get-secrets
      uses: grafana/shared-workflows/actions/get-vault-secrets@main
      with:
        common_secrets: |
          GCP_UPLOAD_ARTIFACTS_KEY=grafana/artifacts-uploader-service-account:'credentials.json'

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ env.GCP_UPLOAD_ARTIFACTS_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Publish report to Cloud Storage
      run: |
        echo "Publish release to Google Cloud Storage:"
        gsutil cp -r ${{ inputs.directory }}. gs://releng-pipeline-artifacts-dev/${{ github.event.repository.name }}/${{ github.event.number }}/Grafana-v${{ matrix.GRAFANA_VERSION }}

    - name: Write report link to summary
      run: echo '<a href="https://storage.googleapis.com/releng-pipeline-artifacts-dev/${{ github.event.repository.name }}/${{ github.event.number }}/Grafana-v${{ matrix.GRAFANA_VERSION }}/index.html">Browse the Playwright report</a>' >> $GITHUB_STEP_SUMMARY
