name: "Publish Playwright report"
description: "Publish a Playwright report to GCS"

inputs:
  grafana-version:
    required: true
    description: "Grafana version used in the test session that generated the report"
  path:
    default: "playwright-report/"
    required: false
    description: "Path to the folder to publish. Defaults to 'playwright-report/'"


runs:
  using: "composite"
  steps:
    - id: get-secrets
      uses: grafana/shared-workflows/actions/get-vault-secrets@main
      with:
        common_secrets: |
          GCP_UPLOAD_ARTIFACTS_KEY=grafana/artifacts-uploader-service-account:'credentials.json'

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ env.GCP_UPLOAD_ARTIFACTS_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Publish report to Cloud Storage
      shell: bash
      run: |
        echo "Publish release to Google Cloud Storage:"
        path=${{inputs.path}}
        last_char=${path: -1}
        [[ $last_char != "/" ]] && path="$path/";
        gsutil cp -r ${{ path }}. gs://releng-pipeline-artifacts-dev/${{ github.event.repository.name }}/${{ github.event.number }}/Grafana-v${{ inputs.grafanaVersion }}

    - name: Write report link to summary
      shell: bash
      run: echo '<a href="https://storage.googleapis.com/releng-pipeline-artifacts-dev/${{ github.event.repository.name }}/${{ github.event.number }}/Grafana-v${{ inputs.grafanaVersion }}/index.html">Browse the Playwright report</a>' >> $GITHUB_STEP_SUMMARY
