// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/grafana/google-sheets-datasource/pkg/apis/googlesheets/v1"
	googlesheetsv1 "github.com/grafana/google-sheets-datasource/pkg/client/applyconfiguration/googlesheets/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDatasources implements DatasourceInterface
type FakeDatasources struct {
	Fake *FakeGooglesheetsV1
	ns   string
}

var datasourcesResource = v1.SchemeGroupVersion.WithResource("datasources")

var datasourcesKind = v1.SchemeGroupVersion.WithKind("Datasource")

// Get takes name of the datasource, and returns the corresponding datasource object, and an error if there is any.
func (c *FakeDatasources) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Datasource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(datasourcesResource, c.ns, name), &v1.Datasource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Datasource), err
}

// List takes label and field selectors, and returns the list of Datasources that match those selectors.
func (c *FakeDatasources) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DatasourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(datasourcesResource, datasourcesKind, c.ns, opts), &v1.DatasourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.DatasourceList{ListMeta: obj.(*v1.DatasourceList).ListMeta}
	for _, item := range obj.(*v1.DatasourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested datasources.
func (c *FakeDatasources) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(datasourcesResource, c.ns, opts))

}

// Create takes the representation of a datasource and creates it.  Returns the server's representation of the datasource, and an error, if there is any.
func (c *FakeDatasources) Create(ctx context.Context, datasource *v1.Datasource, opts metav1.CreateOptions) (result *v1.Datasource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(datasourcesResource, c.ns, datasource), &v1.Datasource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Datasource), err
}

// Update takes the representation of a datasource and updates it. Returns the server's representation of the datasource, and an error, if there is any.
func (c *FakeDatasources) Update(ctx context.Context, datasource *v1.Datasource, opts metav1.UpdateOptions) (result *v1.Datasource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(datasourcesResource, c.ns, datasource), &v1.Datasource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Datasource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDatasources) UpdateStatus(ctx context.Context, datasource *v1.Datasource, opts metav1.UpdateOptions) (*v1.Datasource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(datasourcesResource, "status", c.ns, datasource), &v1.Datasource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Datasource), err
}

// Delete takes name of the datasource and deletes it. Returns an error if one occurs.
func (c *FakeDatasources) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(datasourcesResource, c.ns, name, opts), &v1.Datasource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDatasources) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(datasourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.DatasourceList{})
	return err
}

// Patch applies the patch and returns the patched datasource.
func (c *FakeDatasources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Datasource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(datasourcesResource, c.ns, name, pt, data, subresources...), &v1.Datasource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Datasource), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied datasource.
func (c *FakeDatasources) Apply(ctx context.Context, datasource *googlesheetsv1.DatasourceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Datasource, err error) {
	if datasource == nil {
		return nil, fmt.Errorf("datasource provided to Apply must not be nil")
	}
	data, err := json.Marshal(datasource)
	if err != nil {
		return nil, err
	}
	name := datasource.Name
	if name == nil {
		return nil, fmt.Errorf("datasource.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(datasourcesResource, c.ns, *name, types.ApplyPatchType, data), &v1.Datasource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Datasource), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeDatasources) ApplyStatus(ctx context.Context, datasource *googlesheetsv1.DatasourceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Datasource, err error) {
	if datasource == nil {
		return nil, fmt.Errorf("datasource provided to Apply must not be nil")
	}
	data, err := json.Marshal(datasource)
	if err != nil {
		return nil, err
	}
	name := datasource.Name
	if name == nil {
		return nil, fmt.Errorf("datasource.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(datasourcesResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1.Datasource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Datasource), err
}
