// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/grafana/google-sheets-datasource/pkg/apis/googlesheets/v1"
	googlesheetsv1 "github.com/grafana/google-sheets-datasource/pkg/client/applyconfiguration/googlesheets/v1"
	scheme "github.com/grafana/google-sheets-datasource/pkg/client/clientset/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DatasourcesGetter has a method to return a DatasourceInterface.
// A group's client should implement this interface.
type DatasourcesGetter interface {
	Datasources(namespace string) DatasourceInterface
}

// DatasourceInterface has methods to work with Datasource resources.
type DatasourceInterface interface {
	Create(ctx context.Context, datasource *v1.Datasource, opts metav1.CreateOptions) (*v1.Datasource, error)
	Update(ctx context.Context, datasource *v1.Datasource, opts metav1.UpdateOptions) (*v1.Datasource, error)
	UpdateStatus(ctx context.Context, datasource *v1.Datasource, opts metav1.UpdateOptions) (*v1.Datasource, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Datasource, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DatasourceList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Datasource, err error)
	Apply(ctx context.Context, datasource *googlesheetsv1.DatasourceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Datasource, err error)
	ApplyStatus(ctx context.Context, datasource *googlesheetsv1.DatasourceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Datasource, err error)
	DatasourceExpansion
}

// datasources implements DatasourceInterface
type datasources struct {
	client rest.Interface
	ns     string
}

// newDatasources returns a Datasources
func newDatasources(c *GooglesheetsV1Client, namespace string) *datasources {
	return &datasources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the datasource, and returns the corresponding datasource object, and an error if there is any.
func (c *datasources) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Datasource, err error) {
	result = &v1.Datasource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("datasources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Datasources that match those selectors.
func (c *datasources) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DatasourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DatasourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("datasources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested datasources.
func (c *datasources) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("datasources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a datasource and creates it.  Returns the server's representation of the datasource, and an error, if there is any.
func (c *datasources) Create(ctx context.Context, datasource *v1.Datasource, opts metav1.CreateOptions) (result *v1.Datasource, err error) {
	result = &v1.Datasource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("datasources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(datasource).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a datasource and updates it. Returns the server's representation of the datasource, and an error, if there is any.
func (c *datasources) Update(ctx context.Context, datasource *v1.Datasource, opts metav1.UpdateOptions) (result *v1.Datasource, err error) {
	result = &v1.Datasource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("datasources").
		Name(datasource.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(datasource).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *datasources) UpdateStatus(ctx context.Context, datasource *v1.Datasource, opts metav1.UpdateOptions) (result *v1.Datasource, err error) {
	result = &v1.Datasource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("datasources").
		Name(datasource.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(datasource).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the datasource and deletes it. Returns an error if one occurs.
func (c *datasources) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("datasources").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *datasources) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("datasources").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched datasource.
func (c *datasources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Datasource, err error) {
	result = &v1.Datasource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("datasources").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied datasource.
func (c *datasources) Apply(ctx context.Context, datasource *googlesheetsv1.DatasourceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Datasource, err error) {
	if datasource == nil {
		return nil, fmt.Errorf("datasource provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(datasource)
	if err != nil {
		return nil, err
	}
	name := datasource.Name
	if name == nil {
		return nil, fmt.Errorf("datasource.Name must be provided to Apply")
	}
	result = &v1.Datasource{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("datasources").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *datasources) ApplyStatus(ctx context.Context, datasource *googlesheetsv1.DatasourceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Datasource, err error) {
	if datasource == nil {
		return nil, fmt.Errorf("datasource provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(datasource)
	if err != nil {
		return nil, err
	}

	name := datasource.Name
	if name == nil {
		return nil, fmt.Errorf("datasource.Name must be provided to Apply")
	}

	result = &v1.Datasource{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("datasources").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
