name: E2E tests - Playwright
on:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      matrix: ${{ steps.resolve-versions.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Resolve Grafana E2E versions
        id: resolve-versions
        uses: grafana/plugin-actions/e2e-version@main
        with:
          version-resolver-type: plugin-grafana-dependency

  playwright-tests:
    needs: setup-matrix
    timeout-minutes: 60
    continue-on-error: ${{ needs.setup-matrix }}
    strategy:
      fail-fast: false
      matrix:
        GRAFANA_VERSION: ${{fromJson(needs.setup-matrix.outputs.matrix)}}
    name: E2E Tests - Grafana@${{ matrix.GRAFANA_VERSION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install Mage
        uses: magefile/mage-action@v3
        with:
          install-only: true

      - name: Install yarn dependencies
        run: yarn install --ignore-engines

      - name: Build binaries
        run: mage -v build:linux

      - name: Build frontend
        run: yarn build

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps chromium

      - name: Start Grafana
        run: |
          docker-compose pull
          GRAFANA_VERSION=${{ matrix.GRAFANA_VERSION }} docker-compose up -d

      - name: Wait for Grafana to start
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:3000/'
          responseCode: 200
          timeout: 120000
          interval: 500

      - name: Run Playwright tests
        id: run-tests
        run: yarn playwright test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ steps.run-tests.conclusion == 'success' || steps.run-tests.conclusion == 'failure' && github.event.organization.login != 'grafana' }}
        with:
          name: playwright-report-Grafana-v${{ matrix.GRAFANA_VERSION }}-${{github.run_id}}
          path: packages/plugin-e2e/playwright-report/
          retention-days: 30

      - name: Publish report to GCS
        id: publish-report
        if: ${{ steps.run-tests.conclusion == 'success' || steps.run-tests.conclusion == 'failure' && github.event.organization.login == 'grafana' }}
        # uses: grafana/plugin-actions/publish-report@publish-report
        uses: ./.github/actions/publish-report
        with:
          directory: playwright-report/
